NetCore_Identity/Controllers/FemaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetCore_Identity.Context;

namespace NetCore_Identity.Controllers
{

    [Authorize(Policy = "FemalePolicy")]
    public class FemaleController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        public FemaleController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> AddClaim(int Id)
        {
            var user = _userManager.Users.FirstOrDefault(i => i.Id == Id);
            if ((await _userManager.GetClaimsAsync(user)).Count == 0)
            {
                Claim claim = new Claim("gender", "female");
                await _userManager.AddClaimAsync(user, claim);


            }
            return RedirectToAction("UserList", "Rol");
        }
    }
}

NetCore_Identity/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetCore_Identity.Context;
using NetCore_Identity.Models;
using NetCore_Identity.Views.Rol;

namespace NetCore_Identity.Controllers
{
    [Authorize]//burda işlem yapılacaksa kullanıcı giriş yapmış olsun
    public class RolController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RolController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }
        public IActionResult AddRole()
        {
            return View(new RoleModel());
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(RoleModel model)
        {
            if (ModelState.IsValid)//tanımlanan requiredlerden geçmişşe
            {
                AppRole role = new AppRole
                {
                    Name = model.Name
                };
                var identityResult = await _roleManager.CreateAsync(role);
                if (identityResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in identityResult.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                //Bu hataların gözükmesi için Indexte div eklemeyi unutma
            }
            return View(model);
        }
        public IActionResult UpdateRole(int id)
        {
            var role = _roleManager.Roles.FirstOrDefault(I => I.Id == id);
            //rol boş mu dolu kontrol edilmesi lazımdı.
            RoleUpdateModel model = new RoleUpdateModel
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRole(RoleUpdateModel model)
        {
            var tobeUpdateRole = _roleManager.Roles.
                 Where(I => I.Id == model.Id).FirstOrDefault();
            tobeUpdateRole.Name = model.Name;
            var identityResult = await _roleManager.UpdateAsync(tobeUpdateRole);
            if (identityResult.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in identityResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);

        }
        public async Task<IActionResult> DeleteRole(int id)
        {
            var tobeDeletedRole = _roleManager.Roles.
                FirstOrDefault(I => I.Id == id);
            var identityResult = await _roleManager.DeleteAsync(tobeDeletedRole);
            if (identityResult.Succeeded)
            {
                return RedirectToAction("Index");
            }
            TempData["Errors"] = identityResult.Errors;

            return RedirectToAction("Index");

        }
        public IActionResult UserList()
        {
            return View(_userManager.Users.ToList());
        }
        public async Task<IActionResult> AssignRole(int id)
        {
            var user = _userManager.Users.FirstOrDefault(I => I.Id == id);
            TempData["UserId"] = user.Id;
            var roles = _roleManager.Roles.ToList();
            var userRoles = await _userManager.GetRolesAsync(user);
            List<RoleAssignModel> models = new List<RoleAssignModel>();
            foreach (var item in roles)
            {
                RoleAssignModel model = new RoleAssignModel();
                model.RoleId = item.Id;
                model.Name = item.Name;
                model.Exists = userRoles.Contains(item.Name);
                models.Add(model);
            }
            return View(models);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(List<RoleAssignModel> models)
        {
            var userId = (int)TempData["UserId"];
            var user = _userManager.Users.FirstOrDefault(I => I.Id == userId);

            foreach (var item in models)
            {
                if (item.Exists)//exits clicklenmiş mi?
                {
                    await _userManager.AddToRoleAsync(user, item.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, item.Name);

                }
            }
            return RedirectToAction("UserList");
        }

    }
}

NetCore_Identity/Views/Rol/AddRole.cshtml
@model RoleModel
@{
    ViewData["Title"] = "AddRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="AddRole" method="post" class="w-75 mx-auto p-3">
    <div class=" form-group">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name"></span>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="submit"class=" btn btn-info " value="Kaydet"/>
</form>

NetCore_Identity/Views/Rol/AssignRole.cshtml
@model List<NetCore_Identity.Views.Rol.RoleAssignModel>
@{
    ViewData["Title"] = "AssignRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="AssignRole" method="post" class="w-75 p-3 mx-auto">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="form-check">
            <input type="hidden" asp-for="@Model[i].RoleId" />
            <input type="hidden" asp-for="@Model[i].Name" />
            <input type="checkbox" asp-for="@Model[i].Exists" class="form-check-input" />
            <label class=" form-check-label" for="@Model[i].Exists">@Model[i].Name</label>
        </div>

    }
    <input type="submit" value="Kaydet" class=" btn btn-info " />
</form>

NetCore_Identity/Views/Rol/Index.cshtml
@model List<AppRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="AddRole" asp-controller="Rol" class=" btn btn-info btn-group-sm my-2">Yeni Rol Ekle</a>
<table class="table table-sm table-hover ">
    <tr>
        <td>Ad</td>
        <td>İşlem</td>

    </tr>
    @if (Model.Count > 0)
    {
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    <a asp-action="UpdateRole" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Düzenle</a>
                    <a asp-action="DeleteRole" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td>Sisteminizde kayıtlı rol bulunmuyor</td>
        </tr>
    }

</table>

NetCore_Identity/Views/Rol/UpdateRole.cshtml
@model RoleUpdateModel
@{
    ViewData["Title"] = "UpdateRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form asp-action="UpdateRole" method="post" class="w-75 mx-auto p-3">
    <input type="hidden" asp-for="Id"/>
    <div class=" form-group">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name"></span>
        <input asp-for="Name" class="form-control" />
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="submit" class=" btn btn-info " value="Kaydet" />
</form>

NetCore_Identity/Views/Rol/UserList.cshtml
@model List<AppUser>
@{
    ViewData["Title"] = "UserList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-sm table-hover ">
    <tr>
        <td>Ad</td>
        <td>Roller</td>
        <td>İşlem</td>

    </tr>
    @if (Model.Count > 0)
    {
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td><RolGoster user-id="@item.Id"></RolGoster></td>
                <td>
                    <a asp-action="AssignRole" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Rol Ata</a>
                    <a asp-action="AddClaim"
                       asp-route-id="@item.Id" asp-controller="Female" class="btn btn-info btn-sm">Bayan Claim Ekle</a>
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td>Sisteminizde kayıtlı rol bulunmuyor</td>
        </tr>
    }

</table>