NetCore_Identity/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using NetCore_Identity.Context;
using NetCore_Identity.Models;

namespace NetCore_Identity.Controllers
{
    [Authorize]//kullanıcının giriş yapıp yapmadığını bu attribute ile anlayabiliyoruz.
    public class PanelController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        public PanelController(SignInManager<AppUser> signInManager,UserManager<AppUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);

        }
        public async Task<IActionResult> UpdateUser()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            UserUpdateModel model = new UserUpdateModel()
            {
                Email = user.Email,
                Name = user.Name,
                SurName = user.SurName,
                PhoneNumber = user.SurName,
                PictureUrl = user.PictureUrl

            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserUpdateModel model)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            if (ModelState.IsValid)
            {
                if (model.Picture != null)
                {
                    var uygulamaninCalistigiYer = Directory.GetCurrentDirectory();
                    var uzantı = Path.GetExtension(model.Picture.FileName);
                    var resimAd = Guid.NewGuid() + uzantı;
                    var kaydedilecekYer = uygulamaninCalistigiYer + "/wwwroot/img/" + resimAd;
                    using var stream = new FileStream(kaydedilecekYer, FileMode.Create);
                    await model.Picture.CopyToAsync(stream);
                    user.PictureUrl = resimAd;

                }
                user.Name = model.Name;
                user.SurName = model.SurName;
                user.Email = model.Email;
                user.PhoneNumber = model.PhoneNumber;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);

        }
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

NetCore_Identity/Views/Panel/Index.cshtml
@model AppUser
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <table class="tab-content table-hover table-sm ">

                <tr>
                    <th>İsim:</th>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <th>Soyisim:</th>
                    <td>@Model.SurName</td>
                </tr>
                <tr>
                    <th>Email:</th>
                    <td>@Model.SurName</td>
                </tr>
                <tr>
                    <th>Telefon:</th>
                    <td>@Model.PhoneNumber</td>
                </tr>
            </table>

        </div>
        <div class="col-md-4">
            <img src="~/img/@Model.PictureUrl" alt="@Model.Name" class="w-100 img-fluid img-thumbnail " />
        </div>

    </div>
</div>

NetCore_Identity/Views/Panel/UpdateUser.cshtml
@model UserUpdateModel
@{
    ViewData["Title"] = "UpdateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="UpdateUser" asp-controller="Panel" method="post" class="w-75 mx-auto p-3" enctype="multipart/form-data">
    <div class="form-group">
        @* güncelleme işleminde resim olduğu için enctype belitmemiz gerek *@
        <label asp-for="Name"></label>
        <span asp-validation-for="Name"></span>
        <input asp-for="Name" />
    </div>
    <div class="form-group">
        <label asp-for="SurName"></label>
        <span asp-validation-for="SurName"></span>
        <input asp-for="SurName" />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <span asp-validation-for="Email"></span>
        <input asp-for="Email" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <span asp-validation-for="PhoneNumber"></span>
        <input asp-for="PhoneNumber" />
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-4">
                <label>Bir Önceki Resminiz</label>
                <img src="~/img/@Model.PictureUrl" alt="@Model.Name" class="w-100 img-fluid" />

            </div>
            <div class="col-md-8">
                <input type="file" asp-for="@Model.Picture" />
            </div>
        </div>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <button type="submit" class="btn btn-info btn-sm ">Kaydet</button>

</form>